name = "taglib-audio-processor"
main = "audio-processor.ts"
compatibility_date = "2023-12-01"

# Memory and CPU limits
limits = { cpu_ms = 10000 }

# Environment variables
[vars]
ENVIRONMENT = "production"

# KV storage for WASM binary (Option A)
[[kv_namespaces]]
binding = "TAGLIB_WASM_KV"
id = "your-kv-namespace-id"
preview_id = "your-preview-kv-namespace-id"

# R2 storage for assets (Option B)
[[r2_buckets]]
binding = "ASSETS_BUCKET"
bucket_name = "taglib-assets"
preview_bucket_name = "taglib-assets-preview"

# Build configuration for bundling WASM (Option C - Recommended)
[build]
command = "npm run build"

# Bundle WASM files with the Worker
[[rules]]
type = "Data"
globs = ["**/*.wasm"]
fallthrough = true

# Module rules for ES modules
[[rules]]
type = "ESModule"
globs = ["**/*.ts", "**/*.js"]
fallthrough = true

# Development configuration
[env.development]
name = "taglib-audio-processor-dev"
vars = { ENVIRONMENT = "development" }

# Staging configuration  
[env.staging]
name = "taglib-audio-processor-staging"
vars = { ENVIRONMENT = "staging" }

# Production configuration
[env.production]
name = "taglib-audio-processor"
vars = { ENVIRONMENT = "production" }