name: Minimal Publish

on:
  workflow_dispatch:
    inputs:
      version:
        description: 'Package version to publish'
        required: true
        type: string

jobs:
  publish:
    runs-on: ubuntu-latest
    
    permissions:
      contents: read
      packages: write
      id-token: write
    
    steps:
      - name: Checkout code
        uses: actions/checkout@v4
      
      - name: Verify files exist
        run: |
          echo "=== Repository contents ==="
          ls -la
          echo "=== Build directory ==="
          ls -la build/
          echo "=== Required files ==="
          ls -la build/taglib.wasm build/taglib.js package.json deno.json || echo "Some files missing"
      
      - name: Setup Node.js
        uses: actions/setup-node@v4
        with:
          node-version: '20'
          registry-url: 'https://registry.npmjs.org/'
      
      - name: Install jq
        run: sudo apt-get update && sudo apt-get install -y jq
      
      - name: Update versions
        run: |
          echo "Updating versions to ${{ github.event.inputs.version }}"
          jq '.version = "${{ github.event.inputs.version }}"' package.json > package.tmp.json
          mv package.tmp.json package.json
          jq '.version = "${{ github.event.inputs.version }}"' deno.json > deno.tmp.json  
          mv deno.tmp.json deno.json
          echo "✅ Versions updated"
      
      - name: Test NPM publish (dry run)
        env:
          NODE_AUTH_TOKEN: ${{ secrets.NPM_TOKEN }}
        run: npm publish --dry-run
      
      - name: Setup Deno
        uses: denoland/setup-deno@v1
        with:
          deno-version: v1.x
      
      - name: Test JSR publish (dry run)
        run: deno publish --dry-run