name: Test Checkout

on:
  workflow_dispatch:

jobs:
  test:
    runs-on: ubuntu-latest
    
    steps:
      - name: Test basic checkout
        uses: actions/checkout@v4
      
      - name: List files
        run: |
          echo "=== Repository contents ==="
          ls -la
          echo "=== Git status ==="
          git status || echo "Git status failed"
          echo "=== Build directory ==="
          ls -la build/ || echo "Build directory not found"